export const PROJECTS = [
  {
    imagePath: "/assets/ee/header.webp",
    path: "estilo-elite",
    name: "ESTILO ÉLITE",
    description: "WATCHES SALE",
    paragraph: `Estilo Élite fue creado por Brayan Vargas y Camilo Vargas 
    como un emprendimiento familiar `,
    role: "Developer",
    collaborators: ["Brayan Vargas", "Camilo Vargas"],
    duration: "1 month",
    tools: ["React", "JavaScript"],
    website: "",
    code: "",
    images: [
      { img: "/assets/ee/header.webp", text: "Header de la página" },
      { img: "/assets/ee/filter.webp", text: "Filtrado por marca" },
      { img: "/assets/ee/social.webp", text: "Zona social" },
      { img: "/assets/ee/wpp.webp", text: "WhatsApp integrado " },
    ],
  },
  {
    imagePath: "/assets/rh/header.webp",
    path: "hojarasca",
    name: "HOJARASCA",
    description: "RESTAURANT",
    paragraph: `Hojarasca`,
    role: "Developer",
    collaborators: ["Brayan Vargas", "Camilo Vargas"],
    duration: "6 months",
    tools: ["React", "JavaScript"],
    website: "",
    code: "",
    images: [
      { img: "/assets/rh/header.webp", text: "Header de la página" },
      { img: "/assets/rh/content.webp", text: "Contenido" },
      { img: "/assets/rh/platillos.webp", text: "Platillos y carrito" },
    ],
  },
  {
    imagePath: "/assets/blooma/blooma-phone.webp",
    path: "blooma",
    name: "BLOOMA",
    description: "DESIGNER PLATFORM",
    paragraph: `Blooma`,
    role: "Developer",
    collaborators: ["Brayan Vargas", "Camilo Vargas"],
    duration: "6 months",
    tools: ["React", "JavaScript"],
    website: "",
    code: "",
    images: [
      { img: "/assets/blooma/dashboard.webp", text: "DASHBOARD" },
      { img: "/assets/blooma/storage.webp", text: "ALMACENAMIENTO" },
      { img: "/assets/blooma/files-gestion.webp", text: "Gestion de archivos" },
      {
        img: "/assets/blooma/organization-members.webp",
        text: "Mienmbros de la organizacion",
      },
      { img: "/assets/blooma/service-type.webp", text: "Tipo de servicio" },
      { img: "/assets/blooma/order-details.webp", text: "Detalle de orden" },
      { img: "/assets/blooma/chat.webp", text: "Chat" },
      { img: "/assets/blooma/credits-pricing.webp", text: "Precios" },
    ],
  },
  {
    imagePath: "/assets/nasa.webp",
    path: "nasa-date",
    name: "NASA DATE",
    description: "NASA PHOTOS WITH API",
    paragraph: ``,
    role: "Developer",
    collaborators: ["Brayan Vargas", "Camilo Vargas"],
    duration: "6 months",
    tools: ["React", "JavaScript"],
    website: "",
    code: "",
    images: [
      { img: "/assets/nasa.webp", text: "WATCHES SALE" },
      { img: "/assets/hojarasca.webp", text: "RESTAURANT" },
    ],
  },
  {
    imagePath: "/assets/plain-portfolio/header-portfolio.webp",
    path: "portfolio",
    name: "PORTFOLIO",
    description: "PORTFOLIO PLAIN",
    paragraph: ``,
    role: "Developer",
    collaborators: ["Brayan Vargas", "Camilo Vargas"],
    duration: "6 months",
    tools: ["React", "JavaScript"],
    website: "",
    code: "",
    images: [
      {
        img: "/assets/plain-portfolio/header-portfolio.webp",
        text: "WATCHES SALE",
      },
      { img: "/assets/plain-portfolio/projects.webp", text: "RESTAURANT" },
    ],
  },
  {
    imagePath: "/assets/todo.webp",
    path: "todo",
    name: "TODO APP",
    description: "TODO LIST APP",
    paragraph: ``,
    role: "Developer",
    collaborators: ["Brayan Vargas", "Camilo Vargas"],
    duration: "6 months",
    tools: ["React", "JavaScript"],
    website: "",
    code: "",
    images: [
      {
        img: "/assets/todo.webp",
        text: "WATCHES SALE",
      },
    ],
  },
  {
    imagePath: "/assets/triki.webp",
    path: "triki",
    name: "TRIKI GAME",
    description: "TRIKI GAME",
    paragraph: ``,
    role: "Developer",
    collaborators: ["Brayan Vargas", "Camilo Vargas"],
    duration: "6 months",
    tools: ["React", "JavaScript"],
    website: "",
    code: "",
    images: [
      {
        img: "/assets/triki.webp",
        text: "WATCHES SALE",
      },
    ],
  },
];
