import { Project } from "@/types/Projects";

export const PROJECTS: Project[] = [
  {
    imagePath: "/assets/finance/landing.webp",
    path: "finance",
    name: "finance.name",
    description: "finance.description",
    paragraph: "finance.paragraph",
    role: "finance.role",
    collaborators: ["Brayan Gómez"],
    duration: "finance.duration",
    tools: ["Next JS", "TypeScript", "Tailwind"],
    website: "https://financials-app.vercel.app",
    code: "",
    category: "business",
    images: [
      { img: "/assets/finance/landing.webp", text: "finance.images" },
      { img: "/assets/finance/app.webp", text: "finance.images" },
      { img: "/assets/finance/dashboard.webp", text: "finance.images" },
      { img: "/assets/finance/transactions.webp", text: "finance.images" },
      { img: "/assets/finance/investment.webp", text: "finance.images" },
      { img: "/assets/finance/analytics.webp", text: "finance.images" },
      { img: "/assets/finance/hys.webp", text: "finance.images" },
      { img: "/assets/finance/calculator.webp", text: "finance.images" },
      { img: "/assets/finance/tribute.webp", text: "finance.images" },
    ],
  },
  {
    imagePath: "/assets/estella/hero.webp",
    path: "estella",
    name: "estella.name",
    description: "estella.description",
    paragraph: "estella.paragraph",
    role: "estella.role",
    collaborators: ["Brayan Gómez"],
    duration: "estella.duration",
    tools: ["Next JS", "TypeScript", "Tailwind"],
    website: "https://estella.com.co/",
    code: "",
    category: "business",
    images: [
      { img: "/assets/estella/hero.webp", text: "estella.images" },
      { img: "/assets/estella/collection.webp", text: "estella.images" },
      { img: "/assets/estella/detail.webp", text: "estella.images" },
      { img: "/assets/estella/lookbook.webp", text: "estella.images" },
      { img: "/assets/estella/footer.webp", text: "estella.images" },
    ],
  },
  {
    imagePath: "/assets/impetu/hero.webp",
    path: "impetu",
    name: "impetu.name",
    description: "impetu.description",
    paragraph: "impetu.paragraph",
    role: "impetu.role",
    collaborators: ["Brayan Gómez"],
    duration: "impetu.duration",
    tools: ["Next JS", "TypeScript", "Tailwind"],
    website: "https://impetu-pi.vercel.app/",
    code: "",
    category: "business",
    images: [
      { img: "/assets/impetu/hero.webp", text: "impetu.images" },
      { img: "/assets/impetu/product.webp", text: "impetu.images" },
      { img: "/assets/impetu/how-to-use.webp", text: "impetu.images" },
      { img: "/assets/impetu/detail.webp", text: "impetu.images" },
      { img: "/assets/impetu/speech.webp", text: "impetu.images" },
      { img: "/assets/impetu/footer.webp", text: "impetu.images" },
    ],
  },
  {
    imagePath: "/assets/daniela-photo/hero.webp",
    path: "daniela-photo",
    name: "daniela-photo.name",
    description: "daniela-photo.description",
    paragraph: "daniela-photo.paragraph",
    role: "daniela-photo.role",
    collaborators: ["Brayan Gómez"],
    duration: "daniela-photo.duration",
    tools: ["Next JS", "TypeScript", "Tailwind"],
    website: "https://daniela-photography.vercel.app/",
    code: "",
    category: "business",
    images: [
      { img: "/assets/daniela-photo/hero.webp", text: "daniela-photo.images" },
      {
        img: "/assets/daniela-photo/productions.webp",
        text: "daniela-photo.images",
      },
      { img: "/assets/daniela-photo/details.webp", text: "daniela-photo.images" },
      { img: "/assets/daniela-photo/speech.webp", text: "daniela-photo.images" },
    ],
  },
  {
    imagePath: "/assets/ee/header.webp",
    path: "estilo-elite",
    name: "estilo-elite.name",
    description: "estilo-elite.description",
    paragraph: "estilo-elite.paragraph",
    role: "estilo-elite.role",
    collaborators: ["Brayan Gómez"],
    duration: "estilo-elite.duration",
    tools: ["React", "Tailwind"],
    website: "https://estiloelite.netlify.app/",
    code: "https://github.com/brayang222/EstiloEliteReact.git",
    category: "business",
    images: [
      { img: "/assets/ee/header.webp", text: "estilo-elite.images" },
      { img: "/assets/ee/filter.webp", text: "estilo-elite.images" },
      { img: "/assets/ee/social.webp", text: "estilo-elite.images" },
      { img: "/assets/ee/wpp.webp", text: "estilo-elite.images" },
    ],
  },
  {
    imagePath: "/assets/task-flow/landing-1.webp",
    path: "task-flow",
    name: "task-flow.name",
    description: "task-flow.description",
    paragraph: "task-flow.paragraph",
    role: "task-flow.role",
    collaborators: ["Brayan Gómez"],
    duration: "task-flow.duration",
    tools: ["React", "Node JS", "Tailwind"],
    website: "https://tasks-front-end.vercel.app/",
    code: "https://github.com/brayang222/Tasks-FrontEnd.git",
    category: "practice",
    images: [
      { img: "/assets/task-flow/landing-1.webp", text: "task-flow.images" },
      { img: "/assets/task-flow/landing-2.webp", text: "task-flow.images" },
      { img: "/assets/task-flow/landing-3.webp", text: "task-flow.images" },
      { img: "/assets/task-flow/tasks.webp", text: "task-flow.images" },
      { img: "/assets/task-flow/new-task.webp", text: "task-flow.images" },
      { img: "/assets/task-flow/users.webp", text: "task-flow.images" },
    ],
  },
  {
    imagePath: "/assets/abc/header.webp",
    path: "abc",
    name: "abc.name",
    description: "abc.description",
    paragraph: "abc.paragraph",
    role: "abc.role",
    collaborators: ["Brayan Gómez"],
    duration: "abc.duration",
    tools: ["Next JS", "TypeScript", "Tailwind", "Zustand"],
    website: "https://abc-cinematography.vercel.app",
    code: "https://github.com/brayang222/abc-cinematography.git",
    category: "practice",
    images: [
      { img: "/assets/abc/header.webp", text: "abc.images" },
      { img: "/assets/abc/detalle.webp", text: "abc.images" },
      { img: "/assets/abc/likes.webp", text: "abc.images" },
      {
        img: "/assets/abc/searching.webp",
        text: "abc.images",
      },
    ],
  },
  // {
  //   imagePath: "/assets/chatea/chat.webp",
  //   path: "chatea",
  //   name: "chatea.name",
  //   description: "chatea.description",
  //   paragraph: "chatea.paragraph",
  //   role: "chatea.role",
  //   collaborators: ["Brayan Gómez"],
  //   duration: "chatea.duration",
  //   tools: ["TypeScript", "Tailwind", "React", "Node JS", "WebSockets"],
  //   website: "https://chatea-realtime.vercel.app/",
  //   code: "https://github.com/brayang222/chat-client",
  //   category: "practice",
  //   images: [
  //     { img: "/assets/chatea/login.webp", text: "chatea.images" },
  //     { img: "/assets/chatea/chat.webp", text: "chatea.images" },
  //   ],
  // },
  {
    imagePath: "/assets/proveo/productos.webp",
    path: "proveo",
    name: "proveo.name",
    description: "proveo.description",
    paragraph: "proveo.paragraph",
    role: "proveo.role",
    collaborators: ["Brayan Gómez"],
    duration: "proveo.duration",
    tools: ["Dropi", "Tiendanube"],
    website: "",
    code: "",
    category: "practice",
    images: [
      { img: "/assets/proveo/productos.webp", text: "proveo.images" },
      { img: "/assets/proveo/redes.webp", text: "proveo.images" },
      { img: "/assets/proveo/carrito.webp", text: "proveo.images" },
      {
        img: "/assets/proveo/filtrado.webp",
        text: "proveo.images",
      },
    ],
  },
  {
    imagePath: "/assets/rh/header.webp",
    path: "hojarasca",
    name: "hojarasca.name",
    description: "hojarasca.description",
    paragraph: "hojarasca.paragraph",
    role: "hojarasca.role",
    collaborators: ["Brayan Gómez"],
    duration: "hojarasca.duration",
    tools: ["PHP", "JavaScript", "MySql", "HTML", "CSS", "Bootstrap"],
    website: "",
    code: "https://github.com/brayang222/restaurant-hojarasca.git",
    category: "practice",
    images: [
      { img: "/assets/rh/header.webp", text: "hojarasca.images" },
      { img: "/assets/rh/content.webp", text: "hojarasca.images" },
      { img: "/assets/rh/platillos.webp", text: "hojarasca.images" },
    ],
  },
  {
    imagePath: "/assets/nasa.webp",
    path: "nasa-date",
    name: "nasa.name",
    description: "nasa.description",
    paragraph: "nasa.paragraph",
    role: "nasa.role",
    collaborators: ["Brayan Gómez"],
    duration: "nasa.duration",
    tools: ["JavaScript", "API NASA", "HTML", "CSS"],
    website: "https://astropicturee.netlify.app/",
    code: "https://github.com/brayang222/astronomy-picture",
    category: "practice",
    images: [{ img: "/assets/nasa.webp", text: "nasa.images" }],
  },
  {
    imagePath: "/assets/blooma/blooma-phone.webp",
    path: "blooma",
    name: "blooma.name",
    description: "blooma.description",
    paragraph: "blooma.paragraph",
    role: "blooma.role",
    collaborators: [
      "Brayan Gómez",
      "Andres Velez",
      "Diego Rojas",
      "Alejadro montaña",
    ],
    duration: "blooma.duration",
    tools: ["Next JS", "TypeScript", "Tailwind", "Java", "AWS", "Zustand"],
    website: "https://app-qa.blooma.io/es/employee/my-wallet",
    code: "",
    category: "practice",
    images: [
      { img: "/assets/blooma/dashboard.webp", text: "blooma.images" },
      { img: "/assets/blooma/storage.webp", text: "blooma.images" },
      { img: "/assets/blooma/files-gestion.webp", text: "blooma.images" },
      {
        img: "/assets/blooma/organization-members.webp",
        text: "blooma.images",
      },
      { img: "/assets/blooma/service-type.webp", text: "blooma.images" },
      { img: "/assets/blooma/order-details.webp", text: "blooma.images" },
      { img: "/assets/blooma/chat.webp", text: "blooma.images" },
      { img: "/assets/blooma/credits-pricing.webp", text: "blooma.images" },
    ],
  },
  // {
  //   imagePath: "/assets/plain-portfolio/header-portfolio.webp",
  //   path: "portfolio",
  //   name: "portfolio.name",
  //   description: "portfolio.description",
  //   paragraph: "portfolio.paragraph",
  //   role: "portfolio.role",
  //   collaborators: ["Brayan Gómez"],
  //   duration: "portfolio.duration",
  //   tools: ["HTML", "CSS", "JavaScript"],
  //   website: "https://portfoliobra.netlify.app/",
  //   code: "https://portfoliobra.netlify.app/",
  //   images: [
  //     {
  //       img: "/assets/plain-portfolio/header-portfolio.webp",
  //       text: "portfolio.images",
  //     },
  //     {
  //       img: "/assets/plain-portfolio/projects.webp",
  //       text: "portfolio.images",
  //     },
  //   ],
  // },
  // {
  //   imagePath: "/assets/triki.webp",
  //   path: "triki",
  //   name: "triki.name",
  //   description: "triki.description",
  //   paragraph: "triki.paragraph",
  //   role: "triki.role",
  //   collaborators: ["Brayan Gómez"],
  //   duration: "triki.duration",
  //   tools: ["React", "JavaScript"],
  //   website: "https://trikigame.netlify.app/",
  //   code: "https://github.com/brayang222/tic-tac-toe",
  //   images: [
  //     {
  //       img: "/assets/triki.webp",
  //       text: "triki.images",
  //     },
  //   ],
  // },
  // {
  //   imagePath: "/assets/todo.webp",
  //   path: "todo",
  //   name: "todo.name",
  //   description: "todo.description",
  //   paragraph: "todo.paragraph",
  //   role: "todo.role",
  //   collaborators: ["Brayan Gómez"],
  //   duration: "todo.duration",
  //   tools: ["React", "JavaScript"],
  //   website: "https://listas-tareas.netlify.app/",
  //   code: "https://github.com/brayang222/lista-tareas",
  //   category: "practice",
  //   images: [
  //     {
  //       img: "/assets/todo.webp",
  //       text: "todo.images",
  //     },
  //   ],
  // },
  {
    imagePath: "/assets/white-car/login.webp",
    path: "white-car",
    name: "white-car.name",
    description: "white-car.description",
    paragraph: "white-car.paragraph",
    role: "white-car.role",
    collaborators: ["Brayan Gómez", "Felipe Velez"],
    duration: "white-car.duration",
    tools: [
      "FlutterFlow",
      "Flutter",
      "Dart",
      "Firebase",
      "Google routes, matrix API",
    ],
    website: "https://whitecar.com.co/",
    code: "",
    category: "practice",
    images: [
      { img: "/assets/white-car/header.webp", text: "white-car.images" },
      { img: "/assets/white-car/header-app.webp", text: "white-car.images" },
      { img: "/assets/white-car/offer.webp", text: "white-car.images" },
      { img: "/assets/white-car/pet-trip.webp", text: "white-car.images" },
      { img: "/assets/white-car/login.webp", text: "white-car.images" },
      { img: "/assets/white-car/card-pay.webp", text: "white-car.images" },
    ],
  },
];
